// src/controllers/auth.controller.ts - Enhanced with debugging
import { Request, Response } from 'express';
import authService from '../services/auth.service';
import { AuthRequest } from '../types';

export class AuthController {
  // EXISTING METHOD - Keep for backward compatibility (if needed)
  async register(req: Request, res: Response): Promise<void> {
    try {
      const user = await authService.register(req.body);
      
      res.status(201).json({
        success: true,
        message: 'User registered successfully',
        data: user
      });
    } catch (error: any) {
      res.status(400).json({
        success: false,
        message: error.message || 'Registration failed'
      });
    }
  }

  // LOGIN - Enhanced version
  async login(req: Request, res: Response): Promise<void> {
    try {
      const { email, password } = req.body;

      if (!email || !password) {
        res.status(400).json({
          success: false,
          message: 'Email and password are required'
        });
        return;
      }

      const result = await authService.login({ email, password });
      
      res.status(200).json({
        success: true,
        message: 'Login successful',
        data: result
      });
    } catch (error: any) {
      res.status(401).json({
        success: false,
        message: error.message || 'Login failed'
      });
    }
  }

  // REGISTER ADMIN - Only Superadmin can create admins
  async registerAdmin(req: AuthRequest, res: Response): Promise<void> {
    try {
      const superadminId = req.user?.id;
      
      if (!superadminId) {
        res.status(401).json({
          success: false,
          message: 'Authentication required'
        });
        return;
      }

      const { email, firstName, lastName, phone, department, position, location, salary } = req.body;

      if (!email || !firstName || !lastName) {
        res.status(400).json({
          success: false,
          message: 'Email, first name, and last name are required'
        });
        return;
      }

      const newAdmin = await authService.registerAdmin(
        {
          email,
          password: '', // Generated by service
          firstName,
          lastName,
          phone,
          department,
          position,
          location,
          salary
        },
        superadminId
      );

      res.status(201).json({
        success: true,
        message: 'Admin registered successfully. Invitation email sent.',
        data: newAdmin
      });
    } catch (error: any) {
      res.status(400).json({
        success: false,
        message: error.message || 'Failed to register admin'
      });
    }
  }

  // REGISTER EMPLOYEE - Superadmin or Admin can create employees
  async registerEmployee(req: AuthRequest, res: Response): Promise<void> {
    try {
      const creatorId = req.user?.id;
      
      if (!creatorId) {
        res.status(401).json({
          success: false,
          message: 'Authentication required'
        });
        return;
      }

      const { 
        email, 
        firstName, 
        lastName, 
        phone, 
        department, 
        position, 
        location, 
        salary 
      } = req.body;

      if (!email || !firstName || !lastName || !department || !position) {
        res.status(400).json({
          success: false,
          message: 'Email, first name, last name, department, and position are required'
        });
        return;
      }

      const newEmployee = await authService.registerEmployee(
        {
          email,
          password: '', // Generated by service
          firstName,
          lastName,
          phone,
          department,
          position,
          location,
          salary
        },
        creatorId
      );

      res.status(201).json({
        success: true,
        message: 'Employee registered successfully. Invitation email sent.',
        data: newEmployee
      });
    } catch (error: any) {
      res.status(400).json({
        success: false,
        message: error.message || 'Failed to register employee'
      });
    }
  }

  // CHANGE PASSWORD
  async changePassword(req: AuthRequest, res: Response): Promise<void> {
    try {
      const userId = req.user?.id;
      
      if (!userId) {
        res.status(401).json({
          success: false,
          message: 'Authentication required'
        });
        return;
      }

      const { oldPassword, newPassword, confirmPassword } = req.body;

      if (!oldPassword || !newPassword || !confirmPassword) {
        res.status(400).json({
          success: false,
          message: 'All password fields are required'
        });
        return;
      }

      if (newPassword !== confirmPassword) {
        res.status(400).json({
          success: false,
          message: 'New passwords do not match'
        });
        return;
      }

      if (newPassword.length < 8) {
        res.status(400).json({
          success: false,
          message: 'Password must be at least 8 characters long'
        });
        return;
      }

      const result = await authService.changePassword(userId, oldPassword, newPassword);

      res.status(200).json({
        success: true,
        message: result.message
      });
    } catch (error: any) {
      res.status(400).json({
        success: false,
        message: error.message || 'Failed to change password'
      });
    }
  }

  // GET CURRENT USER (Verify Token) - Enhanced with debugging
  async getCurrentUser(req: AuthRequest, res: Response): Promise<void> {
    console.log('\n🎯 ===== GET CURRENT USER CONTROLLER =====');
    console.log('📍 Route: GET /api/auth/me');
    console.log('🕐 Timestamp:', new Date().toISOString());
    
    try {
      const userId = req.user?.id;
      
      console.log('📊 Request user object:', {
        hasUser: !!req.user,
        userId: userId,
        email: req.user?.email,
        role: req.user?.role,
        fullUserObject: req.user
      });
      
      if (!userId) {
        console.log('❌ No userId in request.user');
        res.status(401).json({
          success: false,
          message: 'Authentication required - no user ID in token'
        });
        return;
      }

      console.log('✅ UserId extracted, calling authService.getProfile()');
      const user = await authService.getProfile(userId);

      console.log('✅ Profile retrieved successfully');
      console.log('🎯 ===== GET CURRENT USER CONTROLLER END =====\n');

      res.status(200).json({
        success: true,
        data: user
      });
    } catch (error: any) {
      console.error('❌ ===== GET CURRENT USER ERROR =====');
      console.error('Error details:', {
        message: error.message,
        name: error.name,
        code: error.code,
        userId: req.user?.id,
        stack: error.stack?.split('\n').slice(0, 3)
      });
      console.error('❌ ===== ERROR END =====\n');
      
      res.status(404).json({
        success: false,
        message: error.message || 'User not found',
        debug: process.env.NODE_ENV === 'development' ? {
          userId: req.user?.id,
          error: error.message,
          timestamp: new Date().toISOString()
        } : undefined
      });
    }
  }

  // GET PROFILE - Enhanced version (alias for getCurrentUser)
  async getProfile(req: AuthRequest, res: Response): Promise<void> {
    console.log('\n🎯 ===== GET PROFILE CONTROLLER =====');
    console.log('📍 Route: GET /api/auth/profile');
    
    try {
      const userId = req.user?.id;
      
      console.log('📊 User ID:', userId);
      
      if (!userId) {
        console.log('❌ No userId in request');
        res.status(401).json({
          success: false,
          message: 'Authentication required'
        });
        return;
      }

      const user = await authService.getProfile(userId);
      
      console.log('✅ Profile retrieved');
      console.log('🎯 ===== GET PROFILE CONTROLLER END =====\n');
      
      res.status(200).json({
        success: true,
        data: user
      });
    } catch (error: any) {
      console.error('❌ Profile error:', error.message);
      
      res.status(404).json({
        success: false,
        message: error.message || 'User not found'
      });
    }
  }

  // LOGOUT - Log the logout action
  async logout(req: AuthRequest, res: Response): Promise<void> {
    try {
      const userId = req.user?.id;
      
      if (!userId) {
        res.status(401).json({
          success: false,
          message: 'Authentication required'
        });
        return;
      }

      const result = await authService.logout(userId);

      res.status(200).json({
        success: true,
        message: result.message
      });
    } catch (error: any) {
      res.status(500).json({
        success: false,
        message: error.message || 'Logout failed'
      });
    }
  }
}

export default new AuthController();